from Logger import Logger
from Paloma import Paloma
from Golondrina import Golondrina


loggerInfo = Logger("INFO")
loggerWarn = Logger("WARN")
loggerError = Logger("ERROR")
loggerInfo.showInfo("LOGGER INFO")
loggerInfo.showWarn("LOGGER INFO")
loggerInfo.showError("LOGGER INFO")
loggerWarn.showInfo("LOGGER WARN")
loggerWarn.showWarn("LOGGER WARN")
loggerWarn.showError("LOGGER WARN")
loggerError.showInfo("LOGGER ERROR")
loggerError.showWarn("LOGGER ERROR")
loggerError.showError("LOGGER ERROR")
print("----------------------------------------------")
pepita = Golondrina(2)
pepon = Golondrina(1)
bombon = Paloma()
print("Energía de Pepita: " + str(pepita.getEnergia()))
pepita.comer(5)
pepita.volar(1)
print("Energía de Pepita: " + str(pepita.getEnergia()))
pepita.comer(20)
pepita.volar(2)
print("Energía de Pepita: " + str(pepita.getEnergia()))
pepita.pescar()
print("Energía de Pepita: " + str(pepita.getEnergia()))
pepita.pescar()
print("Energía de Pepita: " + str(pepita.getEnergia()))
pepita.pescar()
print("Energía de Pepita: " + str(pepita.getEnergia()))
print("----------------------------------------------")
print("Energía de Pepón: " + str(pepon.getEnergia()))
pepon.pescar()
print("Energía de Pepón: " + str(pepon.getEnergia()))
pepon.pescar()
print("Energía de Pepón: " + str(pepon.getEnergia()))
print("----------------------------------------------")
print("Energía de Bombón: " + str(bombon.getEnergia()))
bombon.defecar()
print("Energía de Bombón: " + str(bombon.getEnergia()))
bombon.defecar()
print("Energía de Bombón: " + str(bombon.getEnergia()))